### ISSUE TITLE
Configuration path not set?

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnector#783]
I have the following configuration:

```
services:

  connector:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:6.2.0
    restart: always
    environment:
      - CONFIGURATION_PATH=/config/config.json
    volumes:
      - /app/dbconnector/config.json:/config/config.json
```

But changing the config.json file does not change the configuration of the connector. Is the environment variable CONFIGURATION_PATH correct? If yes, why is the connector configuration not updated? Even syntax errors in the config.json do not prevent the connector from startup.
